name: Convert HTML to APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build APK
        uses: darkshredder/website-to-apk-action@v1.1
        with:
          app-name: "MyVastuTool"
          build-folder-path: "./" # Where your index.html is located
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: apk/ # The folder where the action saves the APK
