name: Convert HTML to APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK
        # FIXED: Using the specific stable version v1.1.2
        uses: darkshredder/web-to-app-action@v1.1.2
        with:
          app-name: "MyVastuTool"
          build-folder-path: "./" 
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: apk/
