name: Convert HTML to APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK
        # FIXED: Correct repository name and version
        uses: darkshredder/web-to-app-action@v1.1.2
        with:
          app-name: "VastuAnalysisTool"
          build-folder-path: "./" 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VastuTool-APK
          path: apk/
